Prevent crashes from "Animators may only be run on Looper threads" 2
revert 3301b7eb08d300e228fac1b80fd6db7de87912e7

Marshmallow only bug
the FATAL EXCEPTION: AsyncTask
java.lang.RuntimeException: An error occurred while executing doInBackground()
Caused by: android.util.AndroidRuntimeException: Animators may only be run on Looper threads

when cpu tab is open

Signed-off-by: Felipe Leon <fglfgl27@gmail.com>